name: flutter build apk

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  apk-build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4.2.2
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      # with:
      #   flutter-version: '3.24.3'
      with:
        channel: stable
        flutter-version-file: pubspec.yaml

    - run: flutter --version

    - run: flutter pub get
    
    - name: Create keystore
      run: |
        echo $ANDROID_KEYSTORE_BASE64 | base64 --decode > keystore.jks
      env:
        ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      
    - name: Build APK with signing
      run: |
        flutter build apk --release \
        -- keystore=keystore.jks \
        --store-password ${{ secrets.JKS_PASSWORD }} \
        --key-password ${{ secrets.JKS_PASSWORD }} \
        --alias ${{ secrets.ANDROID_KEY_ALIAS }}
      env:
        JKS_PASSWORD: ${{ secrets.JKS_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-release.apk


        
